### ISSUE TITLE
[Question] How does one chain the `selector` flag?

### ISSUE THREAD

**Issue by poa00** [lapwat/papeer#19]
In the documentation, `selector` is described as a flag that can be chained in order to capture multiple 'outline' levels of a table of contents, which seems like it would be super useful for mirroring the format of some sites that don't necessarily follow a flat single-level chapter structure.  

So, just as an example, if one were to use `papeer` to download a product manual with the following TOC:

```console
I.  Intro (located at 'section.toc>h2>a')
II. Main Document
A. Chapter One. (located at 'section.toc>h3>ul>li>a')
B. Chapter Two.
...
III. Appendices 
A. Appendix A.
1. Addendum A-1 (located at 'section.toc>h4>ul>li>a')
B. Appendix B
and so on...
```
What would the command syntax look like to include these three selectors chained?

**Comment by lapwat** [comment]
You cannot chain `selector` option for the `ls` command, because it would require to scrape subsequent levels ahead of time just to get the chapters list, which is inefficient. The `selector` option can only be chained in the `get` command. Moreover, the `ls` command can only be used with a `depth` of 1.

In your case, you don't need to chain `selector`, because you are listing chapters at a depth of 1 only. You need to find a selector that includes all the links in the table of content : `section.toc a` would work.

**Comment by poa00** [comment]
Right, I understood as much - sorry if my question was unclear and thank you for getting back to me!  I'm trying to understand the syntax for a `get` command that chains the `selector`.  As for the TOC, that was my just my (BAD) attempt to illustrate a multilevel doc where the chained `selector` would be useful. (Think book 1, 2, 3; part 1, 2, 3, chapter 1, 2, 3; and levels going even deeper.)

At any rate, for the sake of demonstration, where chaining _would be useful_ is this how `selector` should be chained:

```shell
papeer get <URL> --selector 'section.toc>h3>ul>li>a','section.toc>h4>ul>li>a'
```
or is there a different syntax that is appropriate for this?  I did not see any examples/instructions in the documentation.

**Comment by lapwat** [comment]
Ok no worries, the right syntax when chaining selector is:

```sh
papeer get <URL> --selector='section.toc>h3>ul>li>a' --selector='section.toc>h3>ul>li>a'
```

**Comment by poa00** [comment]
Perfect, thank you!! This is an amazing application by the way.  Definitely belongs in all applicable Awesome lists if it's not on them already!
